spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://3.39.191.77:3306/login_test?useSSL=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ex2
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  init:
    sql:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace